### ISSUE TITLE
Release 的标签和实际下载的版本经常不匹配

### ISSUE THREAD

**Issue by SpecterShell** [y-not-u/tinycodes#11]
WinGet 自动更新使用 Release 对应的标签名称作为版本号，但是实际下载的版本以及 `latest.yml` 内显示的版本号经常会落后于这个版本号。

![image](https://user-images.githubusercontent.com/56779163/165274501-c117e1ec-52d7-4e9d-9ace-e28acc536dae.png)

**Comment by y-not-u** [comment]
抱歉，实际情况是我忘记改包的版本号了。
________________________________
From: SpecterShell ***@***.***>
Sent: Tuesday, April 26, 2022 5:58:23 PM
To: y-not-u/tinycodes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [y-not-u/tinycodes] Release 的标签和实际下载的版本经常不匹配 (Issue #11)


WinGet 自动更新使用 Release 对应的标签名称作为版本号，但是实际下载的版本以及 latest.yml 内显示的版本号经常会落后于这个版本号。

[image]<https://user-images.githubusercontent.com/56779163/165274501-c117e1ec-52d7-4e9d-9ace-e28acc536dae.png>

―
